spring.application.name=restaurant-api

# =============================================
# PostgreSQL - Banco de Dados Principal
# =============================================

# =============================================
# JPA / Hibernate
# =============================================
spring.jpa.open-in-view=false
